# Generated by Django 4.1.6 on 2023-03-08 10:16

from django.db import migrations, models
import social.models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='image',
            field=models.ImageField(default='posts/default.jpg', upload_to=social.models.upload_to, verbose_name='Image'),
        ),
    ]
