# Generated by Django 4.1.6 on 2023-03-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_jobpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='reward',
            field=models.FloatField(default=1e-05),
        ),
    ]
