# Generated by Django 4.1.6 on 2023-03-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_jobpost_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='reward',
            field=models.FloatField(),
        ),
    ]
