# Generated by Django 4.1.6 on 2023-04-13 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0004_alter_jobpost_reward'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='social.jobpost')),
            ],
        ),
    ]
